### ISSUE TITLE
App Crashed when starting the project

### ISSUE THREAD

**Issue by kenthellck** [shavindraSN/examen#4] opened 2016-10-25 09:26 UTC
App crashed when running 'npm run develop'

Error message: [nodemon] app crashed - waiting for file changes before starting...

**Comment by ArchchanaKugathsan** [comment] 2016-10-25 09:36
This error is caused by missing npm module `mysql`. Pull latest version of development branch to fix the issue.

**Comment by ArchchanaKugathsan** [comment] 2016-10-25 09:47
Latest version included the missing `mysql` npm module that causes the issue. After pull the latest version do `npm install`. The issue will be fixed

**Closed as completed by ArchchanaKugathsan** 2016-10-25 09:47 UTC
